name: deploy

on:
  push:
    branches:
      - main

  # manually
  workflow_dispatch:


jobs:
  server-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export API_PATH=/var/www/www-root/data/www/api.japit.ru
            echo $API_PATH
            
            # cd to path where code will be located
            cd $API_PATH/
            # systemctl stop
            
            # update code
            ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa_api;
            
            git pull'
            # updating the .env file
            cat <<EOF > $API_PATH/.env
            # start of envfile
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT || '5432' }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            # end of envfile
            EOF
            swift build -c release
            systemctl restart japit
